#!/bin/bash

plan()
{
    matterq-planner --svg $SPOOL_DIR/matterq/images/current.svg $1
    RC=$?
    rsvg $SPOOL_DIR/matterq/images/current.svg \
         $SPOOL_DIR/matterq/images/current.png
    chmod 0666 $SPOOL_DIR/matterq/images/current.svg
    chmod 0666 $SPOOL_DIR/matterq/images/current.png
}


#echo DFC=$datafile_count > /tmp/fs
#if [ "$datafile_count" -gt 1 ]; then
#    echo "multiple data files not supported" >&2
#    exit 2
#fi

source /etc/profile.d/matterq.sh

echo "planning print"

plan $SPOOL_DIR/$DATAFILES

if [ "$RC" -ne 0 ]
then
    plan

    echo "print bed full"
    exit 1
fi

DEPFILE=`mktemp --tmpdir="$SPOOL_DIR/matterq/depositions"`
austerus-verge -d -p $SPOOL_DIR/$DATAFILES > $DEPFILE

echo "processing gcode"

austerus-send -s $SPOOL_DIR/$DATAFILES

echo "finished"

plan

if [ "$RC" -eq 0 ]; then
    exit 0
else
    exit 2
fi
