#!/bin/bash

set -e
set -o pipefail


plan()
{
    set +e
    SHIFT=`matterq-planner --verbose --svg $MQ_SPOOLDIR/images/current.svg $1`
    PLANRC=$?
    set -e

    rsvg $MQ_SPOOLDIR/images/current.svg \
         $MQ_SPOOLDIR/images/current.png
    chmod 0666 $MQ_SPOOLDIR/images/current.svg
    chmod 0666 $MQ_SPOOLDIR/images/current.png
}


#echo DFC=$datafile_count > /tmp/fs
#if [ "$datafile_count" -gt 1 ]; then
#    echo "multiple data files not supported" >&2
#    exit 2
#fi

if [ "$MQ_TESTMODE" -ne 1 ]
then
    source /etc/profile.d/matterq.sh
fi

GCODE=`echo "$SPOOL_DIR/$DATAFILES" | sed 's/\s*$//g'`

echo "planning print"

plan $GCODE

echo "plan=$PLANRC"

case "$PLANRC" in
    0)
        GCODE="$GCODE"
        ;;
    1)
        echo "preshift"
        DX=`echo "$SHIFT" | grep '^X' | awk '{print $2}'`
        DY=`echo "$SHIFT" | grep '^Y' | awk '{print $2}'`
        ZMIN=`echo "$SHIFT" | grep '^Z' | awk '{print $2}'`

	echo "shift"

	OLDGCODE="$GCODE"
        GCODE=`mktemp`
        cat "$OLDGCODE" |
            austerus-shift -x "$DX" -y "$DY" -z "$ZMIN" > "$GCODE"

        if [ "$?" -ne 0 ]
        then
            echo "shift failed"
            exit 1
        fi

	echo "gcodea=$GCODE"
        plan "$GCODE"

        echo "replan=$PLANRC"

        if [ "$PLANRC" -ne 0 ]
        then
            echo "shift replan failed"
            exit 1
        fi
        ;;
    *)
        exit 2
esac

echo "gcode=$GCODE"

DEPFILE=`mktemp --tmpdir="$MQ_SPOOLDIR/depositions"`
austerus-verge -d -p "$GCODE" > "$DEPFILE"

echo "processing gcode"

if [ "$MQ_TESTMODE" -ne 1 ]
then
    austerus-send -s $GCODE
else
    echo austerus-send -s $GCODE
fi

SENDRC=$?

echo "finished"

plan

if [ "$SENDRC" -eq 0 ]; then
    exit 0
else
    exit 2
fi
